# Generated by Django 4.1.1 on 2024-11-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='Offline', max_length=7)),
                ('bond', models.IntegerField(default=0)),
                ('start', models.DateField(auto_now=True)),
                ('img', models.ImageField(default='friend.jpg', upload_to='friend/profile/')),
                ('bio', models.TextField(max_length=250)),
                ('followers', models.ManyToManyField(blank=True, related_name='FriendFollowers', to='user.user')),
                ('following', models.ManyToManyField(blank=True, related_name='FriendFollowing', to='user.user')),
                ('friend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Friend', to='user.user')),
                ('friends', models.ManyToManyField(blank=True, related_name='FriendFriends', to='user.user')),
            ],
        ),
    ]
