# Generated by Django 4.1.1 on 2024-11-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NotificationReciever', to='user.user')),
            ],
        ),
    ]
