# Generated by Django 4.1.1 on 2024-11-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('hours', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(max_length=10)),
                ('followers', models.ManyToManyField(related_name='SpotFollowers', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('created', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpotCreator', to='user.user')),
                ('followers', models.ManyToManyField(related_name='CustomSpotFollowers', to='user.user')),
            ],
        ),
    ]
